=begin
#BWDK API

#<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module OpenapiClient
  class ErrorEnum
    USER_IS_NOT_AUTHENTICATED = "User is not authenticated.".freeze
    ORDER_NOT_FOUND = "Order not found.".freeze
    ORDER_IS_NOT_IN_A_STATE_WHERE_SHIPPING_CAN_BE_SELECTED = "Order is not in a state where shipping can be selected.".freeze
    ORDER_IS_NOT_IN_A_STATE_WHERE_PACKING_CAN_BE_SELECTED = "Order is not in a state where packing can be selected.".freeze
    FAILED_TO_INITIATE_REFUND__PLEASE_TRY_AGAIN_LATER = "Failed to initiate refund. Please try again later.".freeze
    ORDER_IS_EXPIRED_OR_CANCELLED = "Order is expired or cancelled.".freeze
    INVALID_REQUEST_ORIGIN = "Invalid request origin.".freeze
    DIGI_EXPRESS_SHIPPING_METHOD_NOT_FOUND = "Digi Express shipping method not found.".freeze
    ORDER_ADDRESS_NOT_FOUND = "Order address not found.".freeze
    FAILED_TO_FETCH_DIGI_EXPRESS_SHIPPING_TIME_WINDOW_OPTIONS = "Failed to fetch Digi Express shipping time window options.".freeze
    ADDRESS_ID_NOT_FOUND = "Address ID not found.".freeze
    FAILED_TO_CANCEL_SHIPMENT = "Failed to cancel shipment.".freeze
    FAILED_TO_CANCEL_SHIPMENT_IN_THIRD_PARTY_SERVICE = "Failed to cancel shipment in third party service.".freeze
    SHIPMENT_NOT_FOUND = "Shipment not found.".freeze
    SELECTED_SHIPPING_METHOD_IS_NOT_ELIGIBLE_FOR_CANCELLATION = "Selected shipping method is not eligible for cancellation.".freeze
    DIGI_EXPRESS_SHIPMENT_IS_NOT_IN_CANCELABLE_IN_THIS_STATE = "DigiExpress shipment is not in cancelable in this state".freeze
    DIGI_EXPRESS_SHIPMENT_IS_NOT_IN_REVIVEABLE_IN_THIS_STATE = "DigiExpress shipment is not in reviveable in this state".freeze
    FAILED_TO_REVIVE_SHIPMENT_IN_THIRD_PARTY_SERVICE = "Failed to revive shipment in third party service.".freeze
    SELECTED_SHIPPING_METHOD_IS_NOT_ELIGIBLE_FOR_REVIVAL = "Selected shipping method is not eligible for revival.".freeze

    def self.all_vars
      @all_vars ||= [USER_IS_NOT_AUTHENTICATED, ORDER_NOT_FOUND, ORDER_IS_NOT_IN_A_STATE_WHERE_SHIPPING_CAN_BE_SELECTED, ORDER_IS_NOT_IN_A_STATE_WHERE_PACKING_CAN_BE_SELECTED, FAILED_TO_INITIATE_REFUND__PLEASE_TRY_AGAIN_LATER, ORDER_IS_EXPIRED_OR_CANCELLED, INVALID_REQUEST_ORIGIN, DIGI_EXPRESS_SHIPPING_METHOD_NOT_FOUND, ORDER_ADDRESS_NOT_FOUND, FAILED_TO_FETCH_DIGI_EXPRESS_SHIPPING_TIME_WINDOW_OPTIONS, ADDRESS_ID_NOT_FOUND, FAILED_TO_CANCEL_SHIPMENT, FAILED_TO_CANCEL_SHIPMENT_IN_THIRD_PARTY_SERVICE, SHIPMENT_NOT_FOUND, SELECTED_SHIPPING_METHOD_IS_NOT_ELIGIBLE_FOR_CANCELLATION, DIGI_EXPRESS_SHIPMENT_IS_NOT_IN_CANCELABLE_IN_THIS_STATE, DIGI_EXPRESS_SHIPMENT_IS_NOT_IN_REVIVEABLE_IN_THIS_STATE, FAILED_TO_REVIVE_SHIPMENT_IN_THIRD_PARTY_SERVICE, SELECTED_SHIPPING_METHOD_IS_NOT_ELIGIBLE_FOR_REVIVAL].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ErrorEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ErrorEnum"
    end
  end
end
