=begin
#BWDK API

#<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module OpenapiClient
  # Serializer for manager view listing PAID_BY_USER orders
  class MerchantPaidOrderList < ApiModelBase
    attr_accessor :order_uuid

    # شناسه منحصر به فرد سفارش در سیستم فروشنده
    attr_accessor :merchant_order_id

    # شناسه منحصر به فرد فروشنده برای تأیید سفارش
    attr_accessor :merchant_unique_id

    attr_accessor :paid_at

    attr_accessor :refunds_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'order_uuid' => :'order_uuid',
        :'merchant_order_id' => :'merchant_order_id',
        :'merchant_unique_id' => :'merchant_unique_id',
        :'paid_at' => :'paid_at',
        :'refunds_at' => :'refunds_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'order_uuid' => :'String',
        :'merchant_order_id' => :'String',
        :'merchant_unique_id' => :'String',
        :'paid_at' => :'Time',
        :'refunds_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'paid_at',
        :'refunds_at'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::MerchantPaidOrderList` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::MerchantPaidOrderList`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'order_uuid')
        self.order_uuid = attributes[:'order_uuid']
      else
        self.order_uuid = nil
      end

      if attributes.key?(:'merchant_order_id')
        self.merchant_order_id = attributes[:'merchant_order_id']
      else
        self.merchant_order_id = nil
      end

      if attributes.key?(:'merchant_unique_id')
        self.merchant_unique_id = attributes[:'merchant_unique_id']
      else
        self.merchant_unique_id = nil
      end

      if attributes.key?(:'paid_at')
        self.paid_at = attributes[:'paid_at']
      else
        self.paid_at = nil
      end

      if attributes.key?(:'refunds_at')
        self.refunds_at = attributes[:'refunds_at']
      else
        self.refunds_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @order_uuid.nil?
        invalid_properties.push('invalid value for "order_uuid", order_uuid cannot be nil.')
      end

      if @merchant_order_id.nil?
        invalid_properties.push('invalid value for "merchant_order_id", merchant_order_id cannot be nil.')
      end

      if @merchant_unique_id.nil?
        invalid_properties.push('invalid value for "merchant_unique_id", merchant_unique_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @order_uuid.nil?
      return false if @merchant_order_id.nil?
      return false if @merchant_unique_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] order_uuid Value to be assigned
    def order_uuid=(order_uuid)
      if order_uuid.nil?
        fail ArgumentError, 'order_uuid cannot be nil'
      end

      @order_uuid = order_uuid
    end

    # Custom attribute writer method with validation
    # @param [Object] merchant_order_id Value to be assigned
    def merchant_order_id=(merchant_order_id)
      if merchant_order_id.nil?
        fail ArgumentError, 'merchant_order_id cannot be nil'
      end

      @merchant_order_id = merchant_order_id
    end

    # Custom attribute writer method with validation
    # @param [Object] merchant_unique_id Value to be assigned
    def merchant_unique_id=(merchant_unique_id)
      if merchant_unique_id.nil?
        fail ArgumentError, 'merchant_unique_id cannot be nil'
      end

      @merchant_unique_id = merchant_unique_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          order_uuid == o.order_uuid &&
          merchant_order_id == o.merchant_order_id &&
          merchant_unique_id == o.merchant_unique_id &&
          paid_at == o.paid_at &&
          refunds_at == o.refunds_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [order_uuid, merchant_order_id, merchant_unique_id, paid_at, refunds_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
