=begin
#BWDK API

#<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module OpenapiClient
  class OrderItemCreate < ApiModelBase
    # نام کامل محصول شامل تمام مشخصات
    attr_accessor :name

    # قیمت اولیه برای هر واحد بدون تخفیف (به تومان)
    attr_accessor :primary_amount

    # قیمت نهایی برای تمام واحدها بعد از تخفیف (به تومان)
    attr_accessor :amount

    # تعداد واحدهای این کالا در سفارش
    attr_accessor :count

    # مبلغ کل تخفیف برای این کالا (به تومان)
    attr_accessor :discount_amount

    # مبلغ کل مالیات برای این کالا (به تومان)
    attr_accessor :tax_amount

    # آدرس تصویر محصول
    attr_accessor :image_link

    attr_accessor :options

    # Preparation time for the item (in days)
    attr_accessor :preparation_time

    # Weight of the item (in grams)
    attr_accessor :weight

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'primary_amount' => :'primary_amount',
        :'amount' => :'amount',
        :'count' => :'count',
        :'discount_amount' => :'discount_amount',
        :'tax_amount' => :'tax_amount',
        :'image_link' => :'image_link',
        :'options' => :'options',
        :'preparation_time' => :'preparation_time',
        :'weight' => :'weight'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'primary_amount' => :'Integer',
        :'amount' => :'Integer',
        :'count' => :'Integer',
        :'discount_amount' => :'Integer',
        :'tax_amount' => :'Integer',
        :'image_link' => :'String',
        :'options' => :'Array<Option>',
        :'preparation_time' => :'Integer',
        :'weight' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'image_link',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::OrderItemCreate` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::OrderItemCreate`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'primary_amount')
        self.primary_amount = attributes[:'primary_amount']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'count')
        self.count = attributes[:'count']
      else
        self.count = nil
      end

      if attributes.key?(:'discount_amount')
        self.discount_amount = attributes[:'discount_amount']
      end

      if attributes.key?(:'tax_amount')
        self.tax_amount = attributes[:'tax_amount']
      end

      if attributes.key?(:'image_link')
        self.image_link = attributes[:'image_link']
      end

      if attributes.key?(:'options')
        if (value = attributes[:'options']).is_a?(Array)
          self.options = value
        end
      else
        self.options = nil
      end

      if attributes.key?(:'preparation_time')
        self.preparation_time = attributes[:'preparation_time']
      else
        self.preparation_time = 2
      end

      if attributes.key?(:'weight')
        self.weight = attributes[:'weight']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length > 128
        invalid_properties.push('invalid value for "name", the character length must be smaller than or equal to 128.')
      end

      if !@primary_amount.nil? && @primary_amount > 2147483647
        invalid_properties.push('invalid value for "primary_amount", must be smaller than or equal to 2147483647.')
      end

      if !@primary_amount.nil? && @primary_amount < 0
        invalid_properties.push('invalid value for "primary_amount", must be greater than or equal to 0.')
      end

      if !@amount.nil? && @amount > 2147483647
        invalid_properties.push('invalid value for "amount", must be smaller than or equal to 2147483647.')
      end

      if !@amount.nil? && @amount < 0
        invalid_properties.push('invalid value for "amount", must be greater than or equal to 0.')
      end

      if @count.nil?
        invalid_properties.push('invalid value for "count", count cannot be nil.')
      end

      if @count > 32767
        invalid_properties.push('invalid value for "count", must be smaller than or equal to 32767.')
      end

      if @count < 0
        invalid_properties.push('invalid value for "count", must be greater than or equal to 0.')
      end

      if !@discount_amount.nil? && @discount_amount > 2147483647
        invalid_properties.push('invalid value for "discount_amount", must be smaller than or equal to 2147483647.')
      end

      if !@discount_amount.nil? && @discount_amount < 0
        invalid_properties.push('invalid value for "discount_amount", must be greater than or equal to 0.')
      end

      if !@tax_amount.nil? && @tax_amount > 2147483647
        invalid_properties.push('invalid value for "tax_amount", must be smaller than or equal to 2147483647.')
      end

      if !@tax_amount.nil? && @tax_amount < 0
        invalid_properties.push('invalid value for "tax_amount", must be greater than or equal to 0.')
      end

      if !@image_link.nil? && @image_link.to_s.length > 500
        invalid_properties.push('invalid value for "image_link", the character length must be smaller than or equal to 500.')
      end

      if @options.nil?
        invalid_properties.push('invalid value for "options", options cannot be nil.')
      end

      if !@preparation_time.nil? && @preparation_time < 0
        invalid_properties.push('invalid value for "preparation_time", must be greater than or equal to 0.')
      end

      if !@weight.nil? && @weight < 0
        invalid_properties.push('invalid value for "weight", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @name.nil?
      return false if @name.to_s.length > 128
      return false if !@primary_amount.nil? && @primary_amount > 2147483647
      return false if !@primary_amount.nil? && @primary_amount < 0
      return false if !@amount.nil? && @amount > 2147483647
      return false if !@amount.nil? && @amount < 0
      return false if @count.nil?
      return false if @count > 32767
      return false if @count < 0
      return false if !@discount_amount.nil? && @discount_amount > 2147483647
      return false if !@discount_amount.nil? && @discount_amount < 0
      return false if !@tax_amount.nil? && @tax_amount > 2147483647
      return false if !@tax_amount.nil? && @tax_amount < 0
      return false if !@image_link.nil? && @image_link.to_s.length > 500
      return false if @options.nil?
      return false if !@preparation_time.nil? && @preparation_time < 0
      return false if !@weight.nil? && @weight < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length > 128
        fail ArgumentError, 'invalid value for "name", the character length must be smaller than or equal to 128.'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] primary_amount Value to be assigned
    def primary_amount=(primary_amount)
      if primary_amount.nil?
        fail ArgumentError, 'primary_amount cannot be nil'
      end

      if primary_amount > 2147483647
        fail ArgumentError, 'invalid value for "primary_amount", must be smaller than or equal to 2147483647.'
      end

      if primary_amount < 0
        fail ArgumentError, 'invalid value for "primary_amount", must be greater than or equal to 0.'
      end

      @primary_amount = primary_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] amount Value to be assigned
    def amount=(amount)
      if amount.nil?
        fail ArgumentError, 'amount cannot be nil'
      end

      if amount > 2147483647
        fail ArgumentError, 'invalid value for "amount", must be smaller than or equal to 2147483647.'
      end

      if amount < 0
        fail ArgumentError, 'invalid value for "amount", must be greater than or equal to 0.'
      end

      @amount = amount
    end

    # Custom attribute writer method with validation
    # @param [Object] count Value to be assigned
    def count=(count)
      if count.nil?
        fail ArgumentError, 'count cannot be nil'
      end

      if count > 32767
        fail ArgumentError, 'invalid value for "count", must be smaller than or equal to 32767.'
      end

      if count < 0
        fail ArgumentError, 'invalid value for "count", must be greater than or equal to 0.'
      end

      @count = count
    end

    # Custom attribute writer method with validation
    # @param [Object] discount_amount Value to be assigned
    def discount_amount=(discount_amount)
      if discount_amount.nil?
        fail ArgumentError, 'discount_amount cannot be nil'
      end

      if discount_amount > 2147483647
        fail ArgumentError, 'invalid value for "discount_amount", must be smaller than or equal to 2147483647.'
      end

      if discount_amount < 0
        fail ArgumentError, 'invalid value for "discount_amount", must be greater than or equal to 0.'
      end

      @discount_amount = discount_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] tax_amount Value to be assigned
    def tax_amount=(tax_amount)
      if tax_amount.nil?
        fail ArgumentError, 'tax_amount cannot be nil'
      end

      if tax_amount > 2147483647
        fail ArgumentError, 'invalid value for "tax_amount", must be smaller than or equal to 2147483647.'
      end

      if tax_amount < 0
        fail ArgumentError, 'invalid value for "tax_amount", must be greater than or equal to 0.'
      end

      @tax_amount = tax_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] image_link Value to be assigned
    def image_link=(image_link)
      if !image_link.nil? && image_link.to_s.length > 500
        fail ArgumentError, 'invalid value for "image_link", the character length must be smaller than or equal to 500.'
      end

      @image_link = image_link
    end

    # Custom attribute writer method with validation
    # @param [Object] options Value to be assigned
    def options=(options)
      if options.nil?
        fail ArgumentError, 'options cannot be nil'
      end

      @options = options
    end

    # Custom attribute writer method with validation
    # @param [Object] preparation_time Value to be assigned
    def preparation_time=(preparation_time)
      if preparation_time.nil?
        fail ArgumentError, 'preparation_time cannot be nil'
      end

      if preparation_time < 0
        fail ArgumentError, 'invalid value for "preparation_time", must be greater than or equal to 0.'
      end

      @preparation_time = preparation_time
    end

    # Custom attribute writer method with validation
    # @param [Object] weight Value to be assigned
    def weight=(weight)
      if weight.nil?
        fail ArgumentError, 'weight cannot be nil'
      end

      if weight < 0
        fail ArgumentError, 'invalid value for "weight", must be greater than or equal to 0.'
      end

      @weight = weight
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          primary_amount == o.primary_amount &&
          amount == o.amount &&
          count == o.count &&
          discount_amount == o.discount_amount &&
          tax_amount == o.tax_amount &&
          image_link == o.image_link &&
          options == o.options &&
          preparation_time == o.preparation_time &&
          weight == o.weight
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, primary_amount, amount, count, discount_amount, tax_amount, image_link, options, preparation_time, weight].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
