=begin
#BWDK API

#<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module OpenapiClient
  class OrderStatusEnum
    N1 = 1.freeze
    N2 = 2.freeze
    N3 = 3.freeze
    N4 = 4.freeze
    N5 = 5.freeze
    N6 = 6.freeze
    N7 = 7.freeze
    N8 = 8.freeze
    N9 = 9.freeze
    N10 = 10.freeze
    N11 = 11.freeze
    N12 = 12.freeze
    N13 = 13.freeze
    N14 = 14.freeze
    N15 = 15.freeze
    N16 = 16.freeze
    N17 = 17.freeze
    N18 = 18.freeze
    N19 = 19.freeze
    N20 = 20.freeze

    def self.all_vars
      @all_vars ||= [N1, N2, N3, N4, N5, N6, N7, N8, N9, N10, N11, N12, N13, N14, N15, N16, N17, N18, N19, N20].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if OrderStatusEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #OrderStatusEnum"
    end
  end
end
