=begin
#BWDK API

#<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module OpenapiClient
  class PaymentOrder < ApiModelBase
    attr_accessor :final_amount

    attr_accessor :gateway_type

    attr_accessor :gateway_type_display

    attr_accessor :paid_at

    attr_accessor :gateway_name

    attr_accessor :invoice_id

    attr_accessor :settlement_date

    attr_accessor :settlement_status

    attr_accessor :settlement_status_display

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'final_amount' => :'final_amount',
        :'gateway_type' => :'gateway_type',
        :'gateway_type_display' => :'gateway_type_display',
        :'paid_at' => :'paid_at',
        :'gateway_name' => :'gateway_name',
        :'invoice_id' => :'invoice_id',
        :'settlement_date' => :'settlement_date',
        :'settlement_status' => :'settlement_status',
        :'settlement_status_display' => :'settlement_status_display'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'final_amount' => :'Integer',
        :'gateway_type' => :'GatewayTypeEnum',
        :'gateway_type_display' => :'String',
        :'paid_at' => :'String',
        :'gateway_name' => :'String',
        :'invoice_id' => :'String',
        :'settlement_date' => :'String',
        :'settlement_status' => :'Integer',
        :'settlement_status_display' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'gateway_name',
        :'invoice_id',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::PaymentOrder` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::PaymentOrder`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'final_amount')
        self.final_amount = attributes[:'final_amount']
      else
        self.final_amount = nil
      end

      if attributes.key?(:'gateway_type')
        self.gateway_type = attributes[:'gateway_type']
      else
        self.gateway_type = nil
      end

      if attributes.key?(:'gateway_type_display')
        self.gateway_type_display = attributes[:'gateway_type_display']
      else
        self.gateway_type_display = nil
      end

      if attributes.key?(:'paid_at')
        self.paid_at = attributes[:'paid_at']
      else
        self.paid_at = nil
      end

      if attributes.key?(:'gateway_name')
        self.gateway_name = attributes[:'gateway_name']
      else
        self.gateway_name = nil
      end

      if attributes.key?(:'invoice_id')
        self.invoice_id = attributes[:'invoice_id']
      else
        self.invoice_id = nil
      end

      if attributes.key?(:'settlement_date')
        self.settlement_date = attributes[:'settlement_date']
      else
        self.settlement_date = nil
      end

      if attributes.key?(:'settlement_status')
        self.settlement_status = attributes[:'settlement_status']
      else
        self.settlement_status = nil
      end

      if attributes.key?(:'settlement_status_display')
        self.settlement_status_display = attributes[:'settlement_status_display']
      else
        self.settlement_status_display = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @final_amount.nil?
        invalid_properties.push('invalid value for "final_amount", final_amount cannot be nil.')
      end

      if @gateway_type.nil?
        invalid_properties.push('invalid value for "gateway_type", gateway_type cannot be nil.')
      end

      if @gateway_type_display.nil?
        invalid_properties.push('invalid value for "gateway_type_display", gateway_type_display cannot be nil.')
      end

      if @paid_at.nil?
        invalid_properties.push('invalid value for "paid_at", paid_at cannot be nil.')
      end

      if @settlement_date.nil?
        invalid_properties.push('invalid value for "settlement_date", settlement_date cannot be nil.')
      end

      if @settlement_status.nil?
        invalid_properties.push('invalid value for "settlement_status", settlement_status cannot be nil.')
      end

      if @settlement_status_display.nil?
        invalid_properties.push('invalid value for "settlement_status_display", settlement_status_display cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @final_amount.nil?
      return false if @gateway_type.nil?
      return false if @gateway_type_display.nil?
      return false if @paid_at.nil?
      return false if @settlement_date.nil?
      return false if @settlement_status.nil?
      return false if @settlement_status_display.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] final_amount Value to be assigned
    def final_amount=(final_amount)
      if final_amount.nil?
        fail ArgumentError, 'final_amount cannot be nil'
      end

      @final_amount = final_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] gateway_type Value to be assigned
    def gateway_type=(gateway_type)
      if gateway_type.nil?
        fail ArgumentError, 'gateway_type cannot be nil'
      end

      @gateway_type = gateway_type
    end

    # Custom attribute writer method with validation
    # @param [Object] gateway_type_display Value to be assigned
    def gateway_type_display=(gateway_type_display)
      if gateway_type_display.nil?
        fail ArgumentError, 'gateway_type_display cannot be nil'
      end

      @gateway_type_display = gateway_type_display
    end

    # Custom attribute writer method with validation
    # @param [Object] paid_at Value to be assigned
    def paid_at=(paid_at)
      if paid_at.nil?
        fail ArgumentError, 'paid_at cannot be nil'
      end

      @paid_at = paid_at
    end

    # Custom attribute writer method with validation
    # @param [Object] settlement_date Value to be assigned
    def settlement_date=(settlement_date)
      if settlement_date.nil?
        fail ArgumentError, 'settlement_date cannot be nil'
      end

      @settlement_date = settlement_date
    end

    # Custom attribute writer method with validation
    # @param [Object] settlement_status Value to be assigned
    def settlement_status=(settlement_status)
      if settlement_status.nil?
        fail ArgumentError, 'settlement_status cannot be nil'
      end

      @settlement_status = settlement_status
    end

    # Custom attribute writer method with validation
    # @param [Object] settlement_status_display Value to be assigned
    def settlement_status_display=(settlement_status_display)
      if settlement_status_display.nil?
        fail ArgumentError, 'settlement_status_display cannot be nil'
      end

      @settlement_status_display = settlement_status_display
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          final_amount == o.final_amount &&
          gateway_type == o.gateway_type &&
          gateway_type_display == o.gateway_type_display &&
          paid_at == o.paid_at &&
          gateway_name == o.gateway_name &&
          invoice_id == o.invoice_id &&
          settlement_date == o.settlement_date &&
          settlement_status == o.settlement_status &&
          settlement_status_display == o.settlement_status_display
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [final_amount, gateway_type, gateway_type_display, paid_at, gateway_name, invoice_id, settlement_date, settlement_status, settlement_status_display].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
