=begin
#BWDK API

#<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module OpenapiClient
  # Serializer for shipping method details.
  class ShippingMethod < ApiModelBase
    attr_accessor :id

    # نام روش ارسال
    attr_accessor :name

    # توضیحات روش ارسال و جزئیات تحویل آن
    attr_accessor :description

    # نوع روش ارسال: عادی یا دیجی اکسپرس  * `1` - سایر * `2` - دیجی اکسپرس
    attr_accessor :shipping_type

    attr_accessor :get_shipping_type_display

    attr_accessor :shipping_type_display

    # هزینه ارسال برای منطقه اولیه (مثلاً تهران) به تومان
    attr_accessor :cost

    # هزینه ارسال برای مناطق دیگر به تومان
    attr_accessor :secondary_cost

    # حداقل تعداد روزها از تاریخ سفارش تا تحویل
    attr_accessor :minimum_time_sending

    # حداکثر تعداد روزها از تاریخ سفارش تا تحویل
    attr_accessor :maximum_time_sending

    attr_accessor :delivery_time_display

    attr_accessor :delivery_time_range_display

    attr_accessor :inventory_address

    # Whether the shipping method is pay at destination
    attr_accessor :is_pay_at_destination

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'description' => :'description',
        :'shipping_type' => :'shipping_type',
        :'get_shipping_type_display' => :'get_shipping_type_display',
        :'shipping_type_display' => :'shipping_type_display',
        :'cost' => :'cost',
        :'secondary_cost' => :'secondary_cost',
        :'minimum_time_sending' => :'minimum_time_sending',
        :'maximum_time_sending' => :'maximum_time_sending',
        :'delivery_time_display' => :'delivery_time_display',
        :'delivery_time_range_display' => :'delivery_time_range_display',
        :'inventory_address' => :'inventory_address',
        :'is_pay_at_destination' => :'is_pay_at_destination'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'name' => :'String',
        :'description' => :'String',
        :'shipping_type' => :'ShippingTypeEnum',
        :'get_shipping_type_display' => :'String',
        :'shipping_type_display' => :'String',
        :'cost' => :'Integer',
        :'secondary_cost' => :'Integer',
        :'minimum_time_sending' => :'Integer',
        :'maximum_time_sending' => :'Integer',
        :'delivery_time_display' => :'String',
        :'delivery_time_range_display' => :'DeliveryTimeRangeDisplay',
        :'inventory_address' => :'BusinessAddress',
        :'is_pay_at_destination' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::ShippingMethod` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::ShippingMethod`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'shipping_type')
        self.shipping_type = attributes[:'shipping_type']
      end

      if attributes.key?(:'get_shipping_type_display')
        self.get_shipping_type_display = attributes[:'get_shipping_type_display']
      else
        self.get_shipping_type_display = nil
      end

      if attributes.key?(:'shipping_type_display')
        self.shipping_type_display = attributes[:'shipping_type_display']
      else
        self.shipping_type_display = nil
      end

      if attributes.key?(:'cost')
        self.cost = attributes[:'cost']
      end

      if attributes.key?(:'secondary_cost')
        self.secondary_cost = attributes[:'secondary_cost']
      end

      if attributes.key?(:'minimum_time_sending')
        self.minimum_time_sending = attributes[:'minimum_time_sending']
      end

      if attributes.key?(:'maximum_time_sending')
        self.maximum_time_sending = attributes[:'maximum_time_sending']
      end

      if attributes.key?(:'delivery_time_display')
        self.delivery_time_display = attributes[:'delivery_time_display']
      else
        self.delivery_time_display = nil
      end

      if attributes.key?(:'delivery_time_range_display')
        self.delivery_time_range_display = attributes[:'delivery_time_range_display']
      else
        self.delivery_time_range_display = nil
      end

      if attributes.key?(:'inventory_address')
        self.inventory_address = attributes[:'inventory_address']
      else
        self.inventory_address = nil
      end

      if attributes.key?(:'is_pay_at_destination')
        self.is_pay_at_destination = attributes[:'is_pay_at_destination']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length > 64
        invalid_properties.push('invalid value for "name", the character length must be smaller than or equal to 64.')
      end

      if @get_shipping_type_display.nil?
        invalid_properties.push('invalid value for "get_shipping_type_display", get_shipping_type_display cannot be nil.')
      end

      if @shipping_type_display.nil?
        invalid_properties.push('invalid value for "shipping_type_display", shipping_type_display cannot be nil.')
      end

      if !@cost.nil? && @cost > 2147483647
        invalid_properties.push('invalid value for "cost", must be smaller than or equal to 2147483647.')
      end

      if !@cost.nil? && @cost < 0
        invalid_properties.push('invalid value for "cost", must be greater than or equal to 0.')
      end

      if !@secondary_cost.nil? && @secondary_cost > 2147483647
        invalid_properties.push('invalid value for "secondary_cost", must be smaller than or equal to 2147483647.')
      end

      if !@secondary_cost.nil? && @secondary_cost < 0
        invalid_properties.push('invalid value for "secondary_cost", must be greater than or equal to 0.')
      end

      if !@minimum_time_sending.nil? && @minimum_time_sending > 32767
        invalid_properties.push('invalid value for "minimum_time_sending", must be smaller than or equal to 32767.')
      end

      if !@minimum_time_sending.nil? && @minimum_time_sending < 0
        invalid_properties.push('invalid value for "minimum_time_sending", must be greater than or equal to 0.')
      end

      if !@maximum_time_sending.nil? && @maximum_time_sending > 32767
        invalid_properties.push('invalid value for "maximum_time_sending", must be smaller than or equal to 32767.')
      end

      if !@maximum_time_sending.nil? && @maximum_time_sending < 0
        invalid_properties.push('invalid value for "maximum_time_sending", must be greater than or equal to 0.')
      end

      if @delivery_time_display.nil?
        invalid_properties.push('invalid value for "delivery_time_display", delivery_time_display cannot be nil.')
      end

      if @delivery_time_range_display.nil?
        invalid_properties.push('invalid value for "delivery_time_range_display", delivery_time_range_display cannot be nil.')
      end

      if @inventory_address.nil?
        invalid_properties.push('invalid value for "inventory_address", inventory_address cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @name.nil?
      return false if @name.to_s.length > 64
      return false if @get_shipping_type_display.nil?
      return false if @shipping_type_display.nil?
      return false if !@cost.nil? && @cost > 2147483647
      return false if !@cost.nil? && @cost < 0
      return false if !@secondary_cost.nil? && @secondary_cost > 2147483647
      return false if !@secondary_cost.nil? && @secondary_cost < 0
      return false if !@minimum_time_sending.nil? && @minimum_time_sending > 32767
      return false if !@minimum_time_sending.nil? && @minimum_time_sending < 0
      return false if !@maximum_time_sending.nil? && @maximum_time_sending > 32767
      return false if !@maximum_time_sending.nil? && @maximum_time_sending < 0
      return false if @delivery_time_display.nil?
      return false if @delivery_time_range_display.nil?
      return false if @inventory_address.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length > 64
        fail ArgumentError, 'invalid value for "name", the character length must be smaller than or equal to 64.'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] get_shipping_type_display Value to be assigned
    def get_shipping_type_display=(get_shipping_type_display)
      if get_shipping_type_display.nil?
        fail ArgumentError, 'get_shipping_type_display cannot be nil'
      end

      @get_shipping_type_display = get_shipping_type_display
    end

    # Custom attribute writer method with validation
    # @param [Object] shipping_type_display Value to be assigned
    def shipping_type_display=(shipping_type_display)
      if shipping_type_display.nil?
        fail ArgumentError, 'shipping_type_display cannot be nil'
      end

      @shipping_type_display = shipping_type_display
    end

    # Custom attribute writer method with validation
    # @param [Object] cost Value to be assigned
    def cost=(cost)
      if cost.nil?
        fail ArgumentError, 'cost cannot be nil'
      end

      if cost > 2147483647
        fail ArgumentError, 'invalid value for "cost", must be smaller than or equal to 2147483647.'
      end

      if cost < 0
        fail ArgumentError, 'invalid value for "cost", must be greater than or equal to 0.'
      end

      @cost = cost
    end

    # Custom attribute writer method with validation
    # @param [Object] secondary_cost Value to be assigned
    def secondary_cost=(secondary_cost)
      if secondary_cost.nil?
        fail ArgumentError, 'secondary_cost cannot be nil'
      end

      if secondary_cost > 2147483647
        fail ArgumentError, 'invalid value for "secondary_cost", must be smaller than or equal to 2147483647.'
      end

      if secondary_cost < 0
        fail ArgumentError, 'invalid value for "secondary_cost", must be greater than or equal to 0.'
      end

      @secondary_cost = secondary_cost
    end

    # Custom attribute writer method with validation
    # @param [Object] minimum_time_sending Value to be assigned
    def minimum_time_sending=(minimum_time_sending)
      if minimum_time_sending.nil?
        fail ArgumentError, 'minimum_time_sending cannot be nil'
      end

      if minimum_time_sending > 32767
        fail ArgumentError, 'invalid value for "minimum_time_sending", must be smaller than or equal to 32767.'
      end

      if minimum_time_sending < 0
        fail ArgumentError, 'invalid value for "minimum_time_sending", must be greater than or equal to 0.'
      end

      @minimum_time_sending = minimum_time_sending
    end

    # Custom attribute writer method with validation
    # @param [Object] maximum_time_sending Value to be assigned
    def maximum_time_sending=(maximum_time_sending)
      if maximum_time_sending.nil?
        fail ArgumentError, 'maximum_time_sending cannot be nil'
      end

      if maximum_time_sending > 32767
        fail ArgumentError, 'invalid value for "maximum_time_sending", must be smaller than or equal to 32767.'
      end

      if maximum_time_sending < 0
        fail ArgumentError, 'invalid value for "maximum_time_sending", must be greater than or equal to 0.'
      end

      @maximum_time_sending = maximum_time_sending
    end

    # Custom attribute writer method with validation
    # @param [Object] delivery_time_display Value to be assigned
    def delivery_time_display=(delivery_time_display)
      if delivery_time_display.nil?
        fail ArgumentError, 'delivery_time_display cannot be nil'
      end

      @delivery_time_display = delivery_time_display
    end

    # Custom attribute writer method with validation
    # @param [Object] delivery_time_range_display Value to be assigned
    def delivery_time_range_display=(delivery_time_range_display)
      if delivery_time_range_display.nil?
        fail ArgumentError, 'delivery_time_range_display cannot be nil'
      end

      @delivery_time_range_display = delivery_time_range_display
    end

    # Custom attribute writer method with validation
    # @param [Object] inventory_address Value to be assigned
    def inventory_address=(inventory_address)
      if inventory_address.nil?
        fail ArgumentError, 'inventory_address cannot be nil'
      end

      @inventory_address = inventory_address
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          description == o.description &&
          shipping_type == o.shipping_type &&
          get_shipping_type_display == o.get_shipping_type_display &&
          shipping_type_display == o.shipping_type_display &&
          cost == o.cost &&
          secondary_cost == o.secondary_cost &&
          minimum_time_sending == o.minimum_time_sending &&
          maximum_time_sending == o.maximum_time_sending &&
          delivery_time_display == o.delivery_time_display &&
          delivery_time_range_display == o.delivery_time_range_display &&
          inventory_address == o.inventory_address &&
          is_pay_at_destination == o.is_pay_at_destination
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, description, shipping_type, get_shipping_type_display, shipping_type_display, cost, secondary_cost, minimum_time_sending, maximum_time_sending, delivery_time_display, delivery_time_range_display, inventory_address, is_pay_at_destination].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
