=begin
#BWDK API

#<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::MerchantWalletApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MerchantWalletApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::MerchantWalletApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MerchantWalletApi' do
    it 'should create an instance of MerchantWalletApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::MerchantWalletApi)
    end
  end

  # unit tests for wallets_api_v1_wallet_balance_retrieve
  # Get Wallet Balance
  # &lt;div dir&#x3D;\&quot;rtl\&quot; style&#x3D;\&quot;text-align: right;\&quot;&gt;  موجودی کیف پول فروشنده  ## توضیحات  این endpoint موجودی کیف پول فروشنده را برمی‌گرداند. کیف پول برای پرداخت هزینه ارسال دیجی‌اکسپرس استفاده می‌شود. هنگام ثبت مرسوله دیجی‌اکسپرس، هزینه ارسال به‌صورت خودکار از کیف پول کسر می‌شود.  نیاز به **API_KEY** فروشنده دارد.  &lt;/div&gt; 
  # @param [Hash] opts the optional parameters
  # @return [WalletBalance]
  describe 'wallets_api_v1_wallet_balance_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
