=begin
#BWDK API

#<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::OrderShippingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrderShippingApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::OrderShippingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrderShippingApi' do
    it 'should create an instance of OrderShippingApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::OrderShippingApi)
    end
  end

  # unit tests for order_api_v1_manager_cancel_shipment_create
  # Cancel Shipment
  # &lt;div dir&#x3D;\&quot;rtl\&quot; style&#x3D;\&quot;text-align: right;\&quot;&gt;  لغو مرسوله دیجی‌اکسپرس  ## توضیحات  این endpoint برای لغو یک مرسوله ثبت‌شده در سرویس دیجی‌اکسپرس استفاده می‌شود. پس از لغو موفق، مرسوله از صف ارسال خارج می‌شود.  نیاز به **API_KEY** فروشنده دارد.  ## شرایط لغو  * سفارش باید دارای روش ارسال **DigiExpress** باشد * مرسوله باید در وضعیت **در انتظار تحویل به پیک** (Request for Pickup) باشد  &lt;/div&gt;  &#x60;&#x60;&#x60;mermaid sequenceDiagram     participant M as فروشنده     participant API as BWDK API     participant DX as دیجی‌اکسپرس      M-&gt;&gt;API: POST /order/api/v1/manager/{order_uuid}/cancel-shipment/     Note over M,API: Header: X-API-KEY (بدون بدنه)      alt روش ارسال DigiExpress نیست         API--&gt;&gt;M: 400 خطا         Note over API,M: {error: \&quot;Selected shipping method is not DigiExpress\&quot;}     else مرسوله قابل لغو نیست         API--&gt;&gt;M: 400 خطا         Note over API,M: {error: \&quot;...\&quot;}     else لغو موفق         API-&gt;&gt;DX: لغو مرسوله         DX--&gt;&gt;API: تأیید لغو         API--&gt;&gt;M: 200 موفق         Note over API,M: {message, order_uuid, status, status_display}     end &#x60;&#x60;&#x60; 
  # @param order_uuid 
  # @param [Hash] opts the optional parameters
  # @return [MerchantOrderCancelShipmentResponse]
  describe 'order_api_v1_manager_cancel_shipment_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for order_api_v1_manager_change_shipping_method_update
  # Change Shipping Method
  # &lt;div dir&#x3D;\&quot;rtl\&quot; style&#x3D;\&quot;text-align: right;\&quot;&gt;  تغییر روش ارسال سفارش  ## توضیحات  این endpoint به فروشنده اجازه می‌دهد روش ارسال یک سفارش را تغییر دهد. این عملیات معمولاً زمانی استفاده می‌شود که فروشنده بخواهد از DigiExpress به روش ارسال پیش‌فرض (یا بالعکس) تغییر دهد.  نیاز به **API_KEY** فروشنده دارد.  ## پارامترهای ورودی  * **updated_shipping**: شناسه روش ارسال جدید * **preparation_time** (اختیاری): زمان آماده‌سازی (روز) برای DigiExpress  &lt;/div&gt; 
  # @param order_uuid 
  # @param order_detail 
  # @param [Hash] opts the optional parameters
  # @return [OrderDetail]
  describe 'order_api_v1_manager_change_shipping_method_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for order_api_v1_manager_revive_shipment_create
  # Revive Shipment
  # &lt;div dir&#x3D;\&quot;rtl\&quot; style&#x3D;\&quot;text-align: right;\&quot;&gt;  احیای مرسوله دیجی‌اکسپرس  ## توضیحات  این endpoint برای احیای (reactivate) یک مرسوله دیجی‌اکسپرس که قبلاً لغو شده یا در وضعیت غیرفعال است استفاده می‌شود. با ارسال &#x60;preparation_time&#x60; (زمان آماده‌سازی بر حسب روز)، زمان جدید آماده بودن بار تنظیم می‌شود.  نیاز به **API_KEY** فروشنده دارد.  ## پارامترهای ورودی  * **preparation_time** (اختیاری، پیش‌فرض: ۲): تعداد روز تا آماده‌شدن بار برای تحویل به پیک  ## شرایط  * سفارش باید دارای روش ارسال **DigiExpress** باشد * مرسوله باید در وضعیت قابل احیا باشد  &lt;/div&gt;  &#x60;&#x60;&#x60;mermaid sequenceDiagram     participant M as فروشنده     participant API as BWDK API     participant DX as دیجی‌اکسپرس      M-&gt;&gt;API: POST /order/api/v1/manager/{order_uuid}/revive-shipment/     Note over M,API: Header: X-API-KEY&lt;br/&gt;{preparation_time: 2}      alt روش ارسال DigiExpress نیست         API--&gt;&gt;M: 400 خطا         Note over API,M: {error: \&quot;Selected shipping method is not DigiExpress\&quot;}     else احیا موفق         API-&gt;&gt;DX: احیای مرسوله با زمان جدید         DX--&gt;&gt;API: تأیید احیا         API--&gt;&gt;M: 200 موفق         Note over API,M: {message, order_uuid, status, status_display}     end &#x60;&#x60;&#x60; 
  # @param order_uuid 
  # @param [Hash] opts the optional parameters
  # @option opts [ReviveShipment] :revive_shipment 
  # @return [MerchantOrderReviveShipmentResponse]
  describe 'order_api_v1_manager_revive_shipment_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
