=begin
#BWDK API

#<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::TypeNameEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::TypeNameEnum do
  #let(:instance) { OpenapiClient::TypeNameEnum.new }

  describe 'test an instance of TypeNameEnum' do
    it 'should create an instance of TypeNameEnum' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::TypeNameEnum)
    end
  end

end
