=begin
#BWDK API

#<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/api_model_base'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/auth_status_response'
require 'openapi_client/models/business_address'
require 'openapi_client/models/delivery_time_range_display'
require 'openapi_client/models/error_enum'
require 'openapi_client/models/gateway_type_enum'
require 'openapi_client/models/merchant'
require 'openapi_client/models/merchant_order_cancel_shipment_response'
require 'openapi_client/models/merchant_order_refund_response'
require 'openapi_client/models/merchant_order_revive_shipment_response'
require 'openapi_client/models/merchant_paid_order_list'
require 'openapi_client/models/null_enum'
require 'openapi_client/models/option'
require 'openapi_client/models/order_create'
require 'openapi_client/models/order_create_response'
require 'openapi_client/models/order_detail'
require 'openapi_client/models/order_error'
require 'openapi_client/models/order_item_create'
require 'openapi_client/models/order_status_enum'
require 'openapi_client/models/order_user'
require 'openapi_client/models/packing'
require 'openapi_client/models/paginated_merchant_paid_order_list_list'
require 'openapi_client/models/paginated_order_detail_list'
require 'openapi_client/models/payment_order'
require 'openapi_client/models/refund_order'
require 'openapi_client/models/revive_shipment'
require 'openapi_client/models/shipping_method'
require 'openapi_client/models/shipping_type_enum'
require 'openapi_client/models/type_name_enum'
require 'openapi_client/models/update_order_status'
require 'openapi_client/models/verify_order'
require 'openapi_client/models/wallet_balance'

# APIs
require 'openapi_client/api/merchant_orders_api'
require 'openapi_client/api/merchant_wallet_api'
require 'openapi_client/api/order_shipping_api'
require 'openapi_client/api/seller_profile_management_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
