=begin
#BWDK API

#<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'cgi'

module OpenapiClient
  class OrderShippingApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Cancel Shipment
    # <div dir=\"rtl\" style=\"text-align: right;\">  لغو مرسوله دیجی‌اکسپرس  ## توضیحات  این endpoint برای لغو یک مرسوله ثبت‌شده در سرویس دیجی‌اکسپرس استفاده می‌شود. پس از لغو موفق، مرسوله از صف ارسال خارج می‌شود.  نیاز به **API_KEY** فروشنده دارد.  ## شرایط لغو  * سفارش باید دارای روش ارسال **DigiExpress** باشد * مرسوله باید در وضعیت **در انتظار تحویل به پیک** (Request for Pickup) باشد  </div>  ```mermaid sequenceDiagram     participant M as فروشنده     participant API as BWDK API     participant DX as دیجی‌اکسپرس      M->>API: POST /order/api/v1/manager/{order_uuid}/cancel-shipment/     Note over M,API: Header: X-API-KEY (بدون بدنه)      alt روش ارسال DigiExpress نیست         API-->>M: 400 خطا         Note over API,M: {error: \"Selected shipping method is not DigiExpress\"}     else مرسوله قابل لغو نیست         API-->>M: 400 خطا         Note over API,M: {error: \"...\"}     else لغو موفق         API->>DX: لغو مرسوله         DX-->>API: تأیید لغو         API-->>M: 200 موفق         Note over API,M: {message, order_uuid, status, status_display}     end ``` 
    # @param order_uuid [String] 
    # @param [Hash] opts the optional parameters
    # @return [MerchantOrderCancelShipmentResponse]
    def order_api_v1_manager_cancel_shipment_create(order_uuid, opts = {})
      data, _status_code, _headers = order_api_v1_manager_cancel_shipment_create_with_http_info(order_uuid, opts)
      data
    end

    # Cancel Shipment
    # &lt;div dir&#x3D;\&quot;rtl\&quot; style&#x3D;\&quot;text-align: right;\&quot;&gt;  لغو مرسوله دیجی‌اکسپرس  ## توضیحات  این endpoint برای لغو یک مرسوله ثبت‌شده در سرویس دیجی‌اکسپرس استفاده می‌شود. پس از لغو موفق، مرسوله از صف ارسال خارج می‌شود.  نیاز به **API_KEY** فروشنده دارد.  ## شرایط لغو  * سفارش باید دارای روش ارسال **DigiExpress** باشد * مرسوله باید در وضعیت **در انتظار تحویل به پیک** (Request for Pickup) باشد  &lt;/div&gt;  &#x60;&#x60;&#x60;mermaid sequenceDiagram     participant M as فروشنده     participant API as BWDK API     participant DX as دیجی‌اکسپرس      M-&gt;&gt;API: POST /order/api/v1/manager/{order_uuid}/cancel-shipment/     Note over M,API: Header: X-API-KEY (بدون بدنه)      alt روش ارسال DigiExpress نیست         API--&gt;&gt;M: 400 خطا         Note over API,M: {error: \&quot;Selected shipping method is not DigiExpress\&quot;}     else مرسوله قابل لغو نیست         API--&gt;&gt;M: 400 خطا         Note over API,M: {error: \&quot;...\&quot;}     else لغو موفق         API-&gt;&gt;DX: لغو مرسوله         DX--&gt;&gt;API: تأیید لغو         API--&gt;&gt;M: 200 موفق         Note over API,M: {message, order_uuid, status, status_display}     end &#x60;&#x60;&#x60; 
    # @param order_uuid [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(MerchantOrderCancelShipmentResponse, Integer, Hash)>] MerchantOrderCancelShipmentResponse data, response status code and response headers
    def order_api_v1_manager_cancel_shipment_create_with_http_info(order_uuid, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OrderShippingApi.order_api_v1_manager_cancel_shipment_create ...'
      end
      # verify the required parameter 'order_uuid' is set
      if @api_client.config.client_side_validation && order_uuid.nil?
        fail ArgumentError, "Missing the required parameter 'order_uuid' when calling OrderShippingApi.order_api_v1_manager_cancel_shipment_create"
      end
      # resource path
      local_var_path = '/order/api/v1/manager/{order_uuid}/cancel-shipment/'.sub('{' + 'order_uuid' + '}', CGI.escape(order_uuid.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'MerchantOrderCancelShipmentResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['MerchantAPIKeyAuth']

      new_options = opts.merge(
        :operation => :"OrderShippingApi.order_api_v1_manager_cancel_shipment_create",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OrderShippingApi#order_api_v1_manager_cancel_shipment_create\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Change Shipping Method
    # <div dir=\"rtl\" style=\"text-align: right;\">  تغییر روش ارسال سفارش  ## توضیحات  این endpoint به فروشنده اجازه می‌دهد روش ارسال یک سفارش را تغییر دهد. این عملیات معمولاً زمانی استفاده می‌شود که فروشنده بخواهد از DigiExpress به روش ارسال پیش‌فرض (یا بالعکس) تغییر دهد.  نیاز به **API_KEY** فروشنده دارد.  ## پارامترهای ورودی  * **updated_shipping**: شناسه روش ارسال جدید * **preparation_time** (اختیاری): زمان آماده‌سازی (روز) برای DigiExpress  </div> 
    # @param order_uuid [String] 
    # @param order_detail [OrderDetail] 
    # @param [Hash] opts the optional parameters
    # @return [OrderDetail]
    def order_api_v1_manager_change_shipping_method_update(order_uuid, order_detail, opts = {})
      data, _status_code, _headers = order_api_v1_manager_change_shipping_method_update_with_http_info(order_uuid, order_detail, opts)
      data
    end

    # Change Shipping Method
    # &lt;div dir&#x3D;\&quot;rtl\&quot; style&#x3D;\&quot;text-align: right;\&quot;&gt;  تغییر روش ارسال سفارش  ## توضیحات  این endpoint به فروشنده اجازه می‌دهد روش ارسال یک سفارش را تغییر دهد. این عملیات معمولاً زمانی استفاده می‌شود که فروشنده بخواهد از DigiExpress به روش ارسال پیش‌فرض (یا بالعکس) تغییر دهد.  نیاز به **API_KEY** فروشنده دارد.  ## پارامترهای ورودی  * **updated_shipping**: شناسه روش ارسال جدید * **preparation_time** (اختیاری): زمان آماده‌سازی (روز) برای DigiExpress  &lt;/div&gt; 
    # @param order_uuid [String] 
    # @param order_detail [OrderDetail] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(OrderDetail, Integer, Hash)>] OrderDetail data, response status code and response headers
    def order_api_v1_manager_change_shipping_method_update_with_http_info(order_uuid, order_detail, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OrderShippingApi.order_api_v1_manager_change_shipping_method_update ...'
      end
      # verify the required parameter 'order_uuid' is set
      if @api_client.config.client_side_validation && order_uuid.nil?
        fail ArgumentError, "Missing the required parameter 'order_uuid' when calling OrderShippingApi.order_api_v1_manager_change_shipping_method_update"
      end
      # verify the required parameter 'order_detail' is set
      if @api_client.config.client_side_validation && order_detail.nil?
        fail ArgumentError, "Missing the required parameter 'order_detail' when calling OrderShippingApi.order_api_v1_manager_change_shipping_method_update"
      end
      # resource path
      local_var_path = '/order/api/v1/manager/{order_uuid}/change-shipping-method/'.sub('{' + 'order_uuid' + '}', CGI.escape(order_uuid.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(order_detail)

      # return_type
      return_type = opts[:debug_return_type] || 'OrderDetail'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['MerchantAPIKeyAuth']

      new_options = opts.merge(
        :operation => :"OrderShippingApi.order_api_v1_manager_change_shipping_method_update",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:PUT, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OrderShippingApi#order_api_v1_manager_change_shipping_method_update\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Revive Shipment
    # <div dir=\"rtl\" style=\"text-align: right;\">  احیای مرسوله دیجی‌اکسپرس  ## توضیحات  این endpoint برای احیای (reactivate) یک مرسوله دیجی‌اکسپرس که قبلاً لغو شده یا در وضعیت غیرفعال است استفاده می‌شود. با ارسال `preparation_time` (زمان آماده‌سازی بر حسب روز)، زمان جدید آماده بودن بار تنظیم می‌شود.  نیاز به **API_KEY** فروشنده دارد.  ## پارامترهای ورودی  * **preparation_time** (اختیاری، پیش‌فرض: ۲): تعداد روز تا آماده‌شدن بار برای تحویل به پیک  ## شرایط  * سفارش باید دارای روش ارسال **DigiExpress** باشد * مرسوله باید در وضعیت قابل احیا باشد  </div>  ```mermaid sequenceDiagram     participant M as فروشنده     participant API as BWDK API     participant DX as دیجی‌اکسپرس      M->>API: POST /order/api/v1/manager/{order_uuid}/revive-shipment/     Note over M,API: Header: X-API-KEY<br/>{preparation_time: 2}      alt روش ارسال DigiExpress نیست         API-->>M: 400 خطا         Note over API,M: {error: \"Selected shipping method is not DigiExpress\"}     else احیا موفق         API->>DX: احیای مرسوله با زمان جدید         DX-->>API: تأیید احیا         API-->>M: 200 موفق         Note over API,M: {message, order_uuid, status, status_display}     end ``` 
    # @param order_uuid [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [ReviveShipment] :revive_shipment 
    # @return [MerchantOrderReviveShipmentResponse]
    def order_api_v1_manager_revive_shipment_create(order_uuid, opts = {})
      data, _status_code, _headers = order_api_v1_manager_revive_shipment_create_with_http_info(order_uuid, opts)
      data
    end

    # Revive Shipment
    # &lt;div dir&#x3D;\&quot;rtl\&quot; style&#x3D;\&quot;text-align: right;\&quot;&gt;  احیای مرسوله دیجی‌اکسپرس  ## توضیحات  این endpoint برای احیای (reactivate) یک مرسوله دیجی‌اکسپرس که قبلاً لغو شده یا در وضعیت غیرفعال است استفاده می‌شود. با ارسال &#x60;preparation_time&#x60; (زمان آماده‌سازی بر حسب روز)، زمان جدید آماده بودن بار تنظیم می‌شود.  نیاز به **API_KEY** فروشنده دارد.  ## پارامترهای ورودی  * **preparation_time** (اختیاری، پیش‌فرض: ۲): تعداد روز تا آماده‌شدن بار برای تحویل به پیک  ## شرایط  * سفارش باید دارای روش ارسال **DigiExpress** باشد * مرسوله باید در وضعیت قابل احیا باشد  &lt;/div&gt;  &#x60;&#x60;&#x60;mermaid sequenceDiagram     participant M as فروشنده     participant API as BWDK API     participant DX as دیجی‌اکسپرس      M-&gt;&gt;API: POST /order/api/v1/manager/{order_uuid}/revive-shipment/     Note over M,API: Header: X-API-KEY&lt;br/&gt;{preparation_time: 2}      alt روش ارسال DigiExpress نیست         API--&gt;&gt;M: 400 خطا         Note over API,M: {error: \&quot;Selected shipping method is not DigiExpress\&quot;}     else احیا موفق         API-&gt;&gt;DX: احیای مرسوله با زمان جدید         DX--&gt;&gt;API: تأیید احیا         API--&gt;&gt;M: 200 موفق         Note over API,M: {message, order_uuid, status, status_display}     end &#x60;&#x60;&#x60; 
    # @param order_uuid [String] 
    # @param [Hash] opts the optional parameters
    # @option opts [ReviveShipment] :revive_shipment 
    # @return [Array<(MerchantOrderReviveShipmentResponse, Integer, Hash)>] MerchantOrderReviveShipmentResponse data, response status code and response headers
    def order_api_v1_manager_revive_shipment_create_with_http_info(order_uuid, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OrderShippingApi.order_api_v1_manager_revive_shipment_create ...'
      end
      # verify the required parameter 'order_uuid' is set
      if @api_client.config.client_side_validation && order_uuid.nil?
        fail ArgumentError, "Missing the required parameter 'order_uuid' when calling OrderShippingApi.order_api_v1_manager_revive_shipment_create"
      end
      # resource path
      local_var_path = '/order/api/v1/manager/{order_uuid}/revive-shipment/'.sub('{' + 'order_uuid' + '}', CGI.escape(order_uuid.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'revive_shipment'])

      # return_type
      return_type = opts[:debug_return_type] || 'MerchantOrderReviveShipmentResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['MerchantAPIKeyAuth']

      new_options = opts.merge(
        :operation => :"OrderShippingApi.order_api_v1_manager_revive_shipment_create",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OrderShippingApi#order_api_v1_manager_revive_shipment_create\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
